---
title: "SOK-2008-2022-oppgave3"
output: pdf_document
date: "2022-09-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PxWebApiData)
library(tidyverse)
library(OECD)
library(ggrepel) 
```

# Utfordring 3.1

1.

```{r}
arbeidsledighet <- ApiData("https://data.ssb.no/api/v0/no/table/11155/",
                           Kjonn = "0",
                           Alder = c("15-24", "20-64"),
                           UtdNivaa = "TOT",
                           ContentsCode = "ArbLedigProsent",
                           Tid = "2020")

arbeidsledighet <- as.tibble(arbeidsledighet[[2]])
```



```{r}
ggplot(arbeidsledighet, aes(x = Alder, y = value, fill = Alder)) +
  geom_col(col = "black") +
  labs(title = "Arbeidsledighet 2020 i prosent",
       x = "",
       y = "Prosent")
```

2. 

```{r}
dsets<-get_datasets()
search_dataset("wage",dsets)
search_dataset("unemployment",dsets)
```

```{r}
minwage <- get_dataset("MIN2AVE",
                       filter = "USA+CAN+FRA+GBR+DEU+NZL", 
                       pre_formatted = TRUE)
```

```{r}
minwage2019 <- subset(minwage, Time < 2019 & Time >2007 & SERIES=="MEDIAN")
minwage2007_2019 <- subset(minwage2019, Time>2007)
```

```{r}
unempl <- get_dataset("MIG_NUP_RATES_GENDER",
                      filter = "USA+CAN+FRA+GBR+DEU+NZL", 
                      pre_formatted = TRUE)
```

```{r}
unempl2019 <- subset(unempl, Time<2019 & RATE=="U_RATE" & BIRTH=="NB" & GENDER=="TOT")
unempl2007_2019 <- subset(unempl2019, Time>2007)
```

```{r}
minwage_unempl <-left_join(minwage2007_2019, unempl2007_2019, by=c("COUNTRY","Time"))
```

```{r}
complete_minwage_unempl <- na.omit(minwage_unempl)
```

```{r}
complete_minwage_unempl$MinWage_0 <- as.numeric(complete_minwage_unempl$ObsValue.x)

complete_minwage_unempl$UnEmpl <-as.numeric(complete_minwage_unempl$ObsValue.y)
```

```{r}
complete_minwage_unempl$MinWage <- complete_minwage_unempl$MinWage_0 * 100
```

```{r}
minwage_plot <- ggplot(data=complete_minwage_unempl,aes(x=UnEmpl,y=MinWage, group=COUNTRY, color=COUNTRY)) +
  geom_line(aes(group=COUNTRY), size=1) +
  geom_point(size=2.5)+
  labs(x = "Name for x-axis" , y ="Name for y-axis")  + 
  theme(legend.position="none")+
  geom_label_repel(
    data=complete_minwage_unempl %>% group_by(COUNTRY) %>%
      filter(UnEmpl==min(UnEmpl)), 
    aes(UnEmpl, MinWage, fill = factor(COUNTRY), label = sprintf('%s', COUNTRY)),
    color = "black",
    fill = "white")
minwage_plot
```

